### ISSUE TITLE
Error when running on Windows

### ISSUE THREAD

**Issue by MulverineX** [camus-design/svg_to_font#2]
```
W:\workspace\web\refracture\refracture-music\packages\client-flutter>svg_to_font generate --input=./assets/icon/navigation --font-output=./example/assets/font --class-output=./lib/icon     
 Installing npm dependencies ...

added 252 packages, and audited 253 packages in 26s

66 packages are looking for funding
  run `npm fund` for details

3 vulnerabilities (2 moderate, 1 critical)

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.
Unhandled exception:
Unsupported operation: Cannot extract a file path from a c URI
#0      _Uri.toFilePath (dart:core/uri.dart:2847:7)
#1      new File.fromUri (dart:io/file.dart:204:49)
#2      SvgToFontCommand._generateFlutterFile (package:svg_to_font/src/commands/svg_to_font_command.dart:164:37)
#3      SvgToFontCommand.run (package:svg_to_font/src/commands/svg_to_font_command.dart:319:11)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#5      SvgToFontCommandRunner.run (package:svg_to_font/src/runner.dart:27:11)
<asynchronous suspension>
#6      main (file:///C:/Users/mulverine/AppData/Local/Pub/Cache/hosted/pub.dev/svg_to_font-1.0.2/bin/main.dart:6:8)
<asynchronous suspension>
 Installing npm dependencies ...

up to date, audited 253 packages in 813ms

66 packages are looking for funding
  run `npm fund` for details

3 vulnerabilities (2 moderate, 1 critical)

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.
Unhandled exception:
Unsupported operation: Cannot extract a file path from a c URI
#0      _Uri.toFilePath (dart:core/uri.dart:2847:7)
#1      new File.fromUri (dart:io/file.dart:204:49)
#2      SvgToFontCommand._generateFlutterFile (package:svg_to_font/src/commands/svg_to_font_command.dart:164:37)
#3      SvgToFontCommand.run (package:svg_to_font/src/commands/svg_to_font_command.dart:319:11)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#5      SvgToFontCommandRunner.run (package:svg_to_font/src/runner.dart:27:11)
<asynchronous suspension>
#6      main (file:///C:/Users/mulverine/AppData/Local/Pub/Cache/hosted/pub.dev/svg_to_font-1.0.2/bin/main.dart:6:8)
<asynchronous suspension>
```

https://github.com/RefractureMedia/refracture-music/tree/main/packages/client-flutter

**Comment by MulverineX** [comment]
Appears to be an upstream issue https://github.com/tancredi/fantasticon/issues/470
